### ISSUE TITLE
Datapack Error when loaded with minecolonies

### ISSUE THREAD

**Issue by starmun-0010** [al132mc/chem-lib#1]
Chemlib: 1.16.5-1
Minecolonies: 1.0.111
Structrize 0.1.252

Forge: 36.2.8

Chemlib is currently incompatible with minecolonies and causes datapack load errors on world creation.

Log is attached below.
[latest.log](https://github.com/al132mc/chem-lib/files/7499228/latest.log)

**Comment by starmun-0010** [comment]
further info, if you install kubejs + the mods mentioned above and create a new world it causes a crash
[crash-2021-11-08_23.45.51-server.txt](https://github.com/al132mc/chem-lib/files/7499365/crash-2021-11-08_23.45.51-server.txt)
.

**Comment by dacendale** [comment]
Yes I'm seeing this as well with the latest release.

**Comment by Dark-Arcana** [comment]
> Chemlib: 1.16.5-1 Minecolonies: 1.0.111 Structrize 0.1.252
> 
> Forge: 36.2.8
> 
> Chemlib is currently incompatible with minecolonies and causes datapack load errors on world creation.
> 
> Log is attached below. [latest.log](https://github.com/al132mc/chem-lib/files/7499228/latest.log)

Your log indicates that the issue is with Minecolonies. It has nothing to do with ChemLib. There is a null pointer exception when iterating over food ingredients. It's possible that this is an issue with the dank food in 1.16.5, but I'm not longer supporting 1.16.5.
