### ISSUE TITLE
[Bug] Chemlib + Alchemistry

### ISSUE THREAD

**Issue by TheRealM18** [al132mc/chem-lib#10]
Hello SmashingMods,

I currently trying to put both of them together, in a modpack, but still they do not work together.  I have tried both builds from July 6th and July 7th, but still does not work.

My current forge version is:
40.1.54

My current chem lib version is:
1.18.2-2.0.4

My current A Lib version is:
1.18.2-2

My current Alchemistry version is:
1.18.2-5

While the client does load, you can not join the world, or create a world. here is my logs.

[latest.log](https://github.com/SmashingMods/ChemLib/files/9127635/latest.log)

**Comment by Dark-Arcana** [comment]
Latest chemlib does not work with the older alib or alchem. Alib is phased out and no longer needed. Alchem rewrite isn't released yet. I plan to do so very soon. Ironing out a few minor bugs. Or I might release as an alpha.
