### ISSUE TITLE
Aluminium ingots, nuggets and plates forge tag is incorrect.

### ISSUE THREAD

**Issue by korAPUcard** [al132mc/chem-lib#12]
```
forge:ingots/aluminium
forge:nuggets/aluminium
forge:plates/aluminium
```
These forge tags is misspelled to 'Alumi**num**'. So only aluminium ingots, nuggets and plates recipe doesn't recognized in other mods.

Minecraft version is 1.18.2.

**Comment by Dark-Arcana** [comment]
That is the correct spelling in American English for the word "aluminum".

**Comment by Timbroglio** [comment]
Oh dear, it's the eternal American English / English English debate. We should probably have that in the localization.
Also, we should _definitely_ be using whichever forge tag is common practice in other mods.

**Comment by Dark-Arcana** [comment]
The common and standard way to tag "aluminum" is as `forge:ingots/aluminum`. This is how it works for practically all mods. If a modpack maker wants to change how it works, they can write a script using kube/crafttweaker to remove the existing tags and make a new one with their preference.
