### ISSUE TITLE
Config Suggestion

### ISSUE THREAD

**Issue by Intipablo** [al132mc/chem-lib#14]
Just a suggestion for config options to remove stuff like plates, Lamps, and the gases.

**Comment by Dark-Arcana** [comment]
It's not possible to remove items like that from the mod based on a config condition. Technically it is, but it can cause a lot of problems, most prominently with loot tables.

Another way to do this would be to make all loot tables conditional on a config based boolean condition. But I don't think it's a worthwhile feature to add.

Use KubeJS/CraftTweaker to remove the things you don't want to see in game.
