### ISSUE TITLE
Combiner Glitch

### ISSUE THREAD

**Issue by DariusPumma** [al132mc/chem-lib#23]
There is a glitch with the combiner that i have discovered.
When crafting packed ice, needing 36 H2O per crafting space, even if only 1 crafting space has 36 H20 but the rest have only one it starts crafting and doesn't consume any H2O. It just infinitely crafts the ice. I don't know if it works with any other recipes.

https://user-images.githubusercontent.com/69331671/194710000-768c098e-a0e4-49e1-8943-5282e5e21db2.mp4

**Comment by OniyaMCD** [comment]
This is actually an Alchemistry bug - https://github.com/SmashingMods/Alchemistry/issues/249#issue-1382465619

**Comment by Dark-Arcana** [comment]
Almost done with the next update (which has a fix for this).

**Comment by DariusPumma** [comment]
> This is actually an Alchemistry bug - [SmashingMods/Alchemistry#249 (comment)](https://github.com/SmashingMods/Alchemistry/issues/249#issue-1382465619)

Ah, my mistake, I'm sorry i saw Chemlib on the chemicals and thought the combiner, etc were in the same mod. I will close the thread.
