### ISSUE TITLE
Compounds crash wolves

### ISSUE THREAD

**Issue by DaemonUmbra** [al132mc/chem-lib#3]
Due to CompoundItems lacking FoodProperties while returning true in isEdible, the isFood method in WolfEntity will crash with a NullPointerException whenever a player in begging range is holding a compound

**Comment by ghost** [comment]
This is pretty niche, but I confirmed it. It only happens when the compound is one that can be consumed. Fixed in 1.16.5-2. It was a non-issue in 1.18 because of changes made in the port.
