### ISSUE TITLE
Pushing items into dissolver overflows into output

### ISSUE THREAD

**Issue by monkeychex3** [al132mc/chem-lib#42]
Hi, I'm on forge 43.1.55, playing AllTheMods8 (minecraft 1.19.2), and have found issues trying to automate these machines.

When piping items into a dissolver with a pipe, it'll fill up the input slot with 64 items correctly, but the machine doesn't halt further piping. It pipes the other input items into the **output slots**, eventually causing machine operations to cease.

**Comment by Dark-Arcana** [comment]
Wrong mod. ChemLib doesn't have a dissolver. You're looking for Alchemistry. Please report it there.
