### ISSUE TITLE
Polyvinyl Chloride Plate no receipt 

### ISSUE THREAD

**Issue by CedricBojoly** [al132mc/chem-lib#46]
Couldn't find any way to craft Polyvinyl Chloride Plate.

Can you please provide further informations about how to craft Polyvinyl Chloride Plate's ?

**Comment by Dark-Arcana** [comment]
Like many items in ChemLib, there is no way to craft it. You have to use Alchemistry or make your own custom recipes. ChemLib is a library of chemicals that can be used by other mods.

If you use Alchemistry, you can use a compactor to make the plates.
