### ISSUE TITLE
1.20.1 version listed as 1.19.2

### ISSUE THREAD

**Issue by StarWalker1** [al132mc/chem-lib#52]
just a heads up. version 1.20.1-2.0.17 shows in the curseforge launcher as an update for 1.19.2, and causes a crash if installed on 1.19.2

![image](https://github.com/SmashingMods/ChemLib/assets/44377596/fb1e1a2f-267e-461b-9bcb-08267f8f33cf)

**Comment by Dark-Arcana** [comment]
Thanks for the heads up, but I fixed this right after it happened. But CurseForge pushed it already to the launcher. It might take time for it to fix itself.
