### ISSUE TITLE
Chemlib v 1.18.2-2.0.2 causes a datapack error

### ISSUE THREAD

**Issue by MisterObvious25** [al132mc/chem-lib#8]
When trying to use alchemistry with the newest version of Chemlib 1.18.2-2.0.2, The launcher shows the following screen
![image](https://user-images.githubusercontent.com/19491809/173241336-f7f3b463-6b24-4402-8b85-942f1beacf35.png)

**Steps to recreate**

1. Create a new 1.18.2 profile with the Curseforge launcher
2. Install the following mods + versions
    - Forge 40.0.54
    - alib-1.18.2-2
    - alchemistry-1.18.2-5
    - chemlib-1.18.2-2.0.2
3. Launch Minecraft
4. Start a new world or load a previously created world

**Expected behavior**
Minecraft creating a new world of opening the previously created world

**Mod versions**
alib-1.18.2-2
alchemistry-1.18.2-5
chemlib-1.18.2-2.0.2
Forge 40.0.54
Minecraft 1.18.2

**Log file**
[https://justpaste.it/6ohmo](https://justpaste.it/6ohmo)

**Other useful information**
- I've tested this in a clean world
- Bumping up the forge version does not prevent the error
- When using a older version of chemlib(1.18.2-2)no problem arises, therefore i think the problem is in the rewrite of chemlib

**Comment by OniyaMCD** [comment]
https://github.com/SmashingMods/Alchemistry/issues/189
